import type {
  Account,
  AccountCoverageMetric,
  ActivityEvent,
  Agent,
  AgentPerformanceSnapshot,
  Contact,
  FieldAgent,
  HistoricalTrendPoint,
  InterviewQuestion,
  ManagerInsight,
  Opportunity,
  ScheduledVisit,
  Task,
  TerritoryMetric,
} from './types';

export const demoAgent: Agent = {
  id: 'agent-1',
  name: 'Sofia Rivera',
  territory: 'Mexico City West',
  streakDays: 4,
};

export const demoLocation = {
  latitude: 19.4328,
  longitude: -99.1334,
};

export const accounts: Account[] = [
  {
    id: 'acct-acme',
    name: 'Acme Corporation',
    industry: 'Retail Distribution',
    address: 'Av. Paseo de la Reforma 222, Juarez, Mexico City',
    latitude: 19.4308,
    longitude: -99.1571,
    summary: 'Expanding regional distribution and evaluating route optimization software.',
    status: 'Expansion candidate',
    risks: ['Procurement cycle is slow'],
    type: 'Retail distributor',
    tier: 'Enterprise',
    lastInteractionDate: '2026-06-12',
    engagementRisk: 'Low',
    nextAction: 'Confirm decision timeline',
    isNearbyCandidate: true,
  },
  {
    id: 'acct-globex',
    name: 'Globex Manufacturing',
    industry: 'Industrial Manufacturing',
    address: 'Rio Lerma 167, Cuauhtemoc, Mexico City',
    latitude: 19.4269,
    longitude: -99.1692,
    summary: 'Operations team needs better demand visibility for field sales.',
    status: 'Negotiation',
    risks: ['Budget approval depends on CFO review'],
    type: 'Manufacturing account',
    tier: 'Strategic',
    lastInteractionDate: '2026-06-03',
    engagementRisk: 'High',
    nextAction: 'Review CFO approval path',
    isNearbyCandidate: true,
    hasEscalation: true,
  },
  {
    id: 'acct-initech',
    name: 'Initech Solutions',
    industry: 'Technology Services',
    address: 'Durango 205, Roma Norte, Mexico City',
    latitude: 19.4197,
    longitude: -99.1647,
    summary: 'Existing customer interested in automating follow-up tasks.',
    status: 'Active customer',
    risks: [],
    type: 'Technology customer',
    tier: 'Growth',
    lastInteractionDate: '2026-06-10',
    engagementRisk: 'Low',
    nextAction: 'Schedule onboarding',
    isNearbyCandidate: true,
  },
  {
    id: 'acct-horizon',
    name: 'Horizon Builders',
    industry: 'Construction',
    address: 'Av. Chapultepec 398, Roma Norte, Mexico City',
    latitude: 19.4211,
    longitude: -99.1616,
    summary: 'Regional builder evaluating field execution analytics for project sales teams.',
    status: 'Open opportunity',
    risks: ['Proposal follow-up is overdue'],
    type: 'Construction group',
    tier: 'Enterprise',
    lastInteractionDate: '2026-05-24',
    engagementRisk: 'Medium',
    nextAction: 'Follow up on proposal economics',
    isNearbyCandidate: true,
  },
  {
    id: 'acct-northstar',
    name: 'Northstar Medical Supply',
    industry: 'Healthcare Supply',
    address: 'Hamburgo 182, Juarez, Mexico City',
    latitude: 19.4261,
    longitude: -99.1612,
    summary: 'Procurement team needs stronger visit traceability and account coverage alerts.',
    status: 'Active customer',
    risks: ['Contract renewal window opens this month'],
    type: 'Healthcare supplier',
    tier: 'Strategic',
    lastInteractionDate: '2026-06-01',
    engagementRisk: 'Medium',
    nextAction: 'Confirm renewal stakeholders',
    isNearbyCandidate: true,
  },
  {
    id: 'acct-urban-foods',
    name: 'Urban Foods Group',
    industry: 'Food Service',
    address: 'Orizaba 76, Roma Norte, Mexico City',
    latitude: 19.4185,
    longitude: -99.1587,
    summary: 'Multi-location operator with a stalled expansion discussion.',
    status: 'Needs follow-up',
    risks: ['No response after pricing discussion'],
    type: 'Food service operator',
    tier: 'Growth',
    lastInteractionDate: '2026-05-20',
    engagementRisk: 'High',
    nextAction: 'Recover pricing discussion',
    isNearbyCandidate: true,
    hasEscalation: true,
  },
  {
    id: 'acct-atlas',
    name: 'Atlas Logistics',
    industry: 'Logistics',
    address: 'Londres 247, Juarez, Mexico City',
    latitude: 19.4247,
    longitude: -99.1667,
    summary: 'Operations leadership asked for a quick field workflow benchmark.',
    status: 'Active prospect',
    risks: [],
    type: 'Logistics operator',
    tier: 'Core',
    lastInteractionDate: '2026-06-06',
    engagementRisk: 'Low',
    nextAction: 'Share benchmark deck',
    isNearbyCandidate: true,
  },
  {
    id: 'acct-pinnacle',
    name: 'Pinnacle Retail Partners',
    industry: 'Retail',
    address: 'Genova 33, Juarez, Mexico City',
    latitude: 19.4277,
    longitude: -99.1645,
    summary: 'Retail buying team is comparing vendors before a Q3 rollout.',
    status: 'Competitive evaluation',
    risks: ['Competitor has executive sponsor'],
    type: 'Retail buying group',
    tier: 'Enterprise',
    lastInteractionDate: '2026-05-29',
    engagementRisk: 'Medium',
    nextAction: 'Book executive sponsor call',
    isNearbyCandidate: true,
  },
];

export const fieldAgents: FieldAgent[] = [
  {
    ...demoAgent,
    avatarInitials: 'SR',
    status: 'OnSchedule',
    latitude: 19.4308,
    longitude: -99.1571,
    currentCustomer: 'Acme Corporation',
    completionPercent: 86,
    crmCompletionRate: 94,
    routeEfficiency: 91,
    onTimeArrivalRate: 96,
    productiveHours: 6.4,
  },
  {
    id: 'agent-2',
    name: 'Ruben Ortega',
    territory: 'Mexico City North',
    streakDays: 2,
    avatarInitials: 'RO',
    status: 'AtRisk',
    latitude: 19.4552,
    longitude: -99.1458,
    currentCustomer: 'Northstar Logistics',
    completionPercent: 58,
    crmCompletionRate: 68,
    routeEfficiency: 74,
    onTimeArrivalRate: 71,
    productiveHours: 4.2,
  },
  {
    id: 'agent-3',
    name: 'Maria Santos',
    territory: 'Mexico City South',
    streakDays: 6,
    avatarInitials: 'MS',
    status: 'InMeeting',
    latitude: 19.3849,
    longitude: -99.1621,
    currentCustomer: 'Initech Solutions',
    completionPercent: 78,
    crmCompletionRate: 87,
    routeEfficiency: 83,
    onTimeArrivalRate: 89,
    productiveHours: 5.7,
  },
  {
    id: 'agent-4',
    name: 'John Miller',
    territory: 'Mexico City East',
    streakDays: 0,
    avatarInitials: 'JM',
    status: 'Missed',
    latitude: 19.4216,
    longitude: -99.0862,
    currentCustomer: 'Globex Manufacturing',
    completionPercent: 39,
    crmCompletionRate: 52,
    routeEfficiency: 61,
    onTimeArrivalRate: 48,
    productiveHours: 3.1,
  },
  {
    id: 'agent-5',
    name: 'Elena Vega',
    territory: 'Mexico City West',
    streakDays: 3,
    avatarInitials: 'EV',
    status: 'Offline',
    latitude: 19.4082,
    longitude: -99.1896,
    completionPercent: 64,
    crmCompletionRate: 77,
    routeEfficiency: 79,
    onTimeArrivalRate: 84,
    productiveHours: 4.8,
  },
];

export const agentPerformanceSnapshots: AgentPerformanceSnapshot[] = [
  {
    agentId: 'agent-1',
    visitsCompleted: 6,
    visitsScheduled: 7,
    opportunityUpdates: 4,
    followUpTasksCompleted: 8,
    followUpTasksOpen: 2,
    overdueTasks: 0,
    averageResponseHours: 1.4,
    crmUpdatesSubmitted: 12,
    missedVisits: 0,
  },
  {
    agentId: 'agent-2',
    visitsCompleted: 4,
    visitsScheduled: 7,
    opportunityUpdates: 2,
    followUpTasksCompleted: 4,
    followUpTasksOpen: 5,
    overdueTasks: 2,
    averageResponseHours: 5.8,
    crmUpdatesSubmitted: 7,
    missedVisits: 1,
  },
  {
    agentId: 'agent-3',
    visitsCompleted: 5,
    visitsScheduled: 6,
    opportunityUpdates: 3,
    followUpTasksCompleted: 7,
    followUpTasksOpen: 2,
    overdueTasks: 0,
    averageResponseHours: 2.1,
    crmUpdatesSubmitted: 10,
    missedVisits: 0,
  },
  {
    agentId: 'agent-4',
    visitsCompleted: 3,
    visitsScheduled: 8,
    opportunityUpdates: 1,
    followUpTasksCompleted: 3,
    followUpTasksOpen: 6,
    overdueTasks: 4,
    averageResponseHours: 8.6,
    crmUpdatesSubmitted: 5,
    missedVisits: 2,
  },
  {
    agentId: 'agent-5',
    visitsCompleted: 4,
    visitsScheduled: 6,
    opportunityUpdates: 2,
    followUpTasksCompleted: 5,
    followUpTasksOpen: 3,
    overdueTasks: 1,
    averageResponseHours: 3.9,
    crmUpdatesSubmitted: 8,
    missedVisits: 0,
  },
];

export const managerInsights: ManagerInsight[] = [
  {
    id: 'insight-1',
    agentId: 'agent-4',
    severity: 'critical',
    category: 'risk',
    title: 'Missed visits are affecting coverage',
    message: 'John has 2 missed visits and the lowest route adherence today.',
    recommendedAction: 'Reassign the last east-side stop and schedule a coaching check-in.',
  },
  {
    id: 'insight-2',
    agentId: 'agent-2',
    severity: 'warning',
    category: 'crm',
    title: 'CRM updates are falling behind',
    message: 'Ruben has open follow-ups and a CRM completion rate below team target.',
    recommendedAction: 'Ask for same-day notes before the next customer meeting.',
  },
  {
    id: 'insight-3',
    accountId: 'acct-globex',
    severity: 'warning',
    category: 'coverage',
    title: 'Globex needs manager attention',
    message: 'The account has proposal-stage pipeline and low engagement frequency.',
    recommendedAction: 'Join the next review call and confirm the CFO approval path.',
  },
  {
    id: 'insight-4',
    agentId: 'agent-1',
    severity: 'info',
    category: 'coaching',
    title: 'Use Sofia as a playbook example',
    message: 'Sofia leads the team in completion, CRM quality, and on-time arrival.',
    recommendedAction: 'Share her visit prep checklist with the wider team.',
  },
  {
    id: 'insight-5',
    severity: 'info',
    category: 'productivity',
    title: 'West territory is ahead of pace',
    message: 'West-side agents are completing visits with strong travel efficiency.',
    recommendedAction: 'Keep the route sequence and use overflow capacity for inactive accounts.',
  },
];

export const historicalTrends: HistoricalTrendPoint[] = [
  { date: '2026-05-27', teamCompletion: 62, crmCompletion: 69, visitsCompleted: 17, tasksCompleted: 20 },
  { date: '2026-05-28', teamCompletion: 66, crmCompletion: 72, visitsCompleted: 19, tasksCompleted: 23 },
  { date: '2026-05-29', teamCompletion: 71, crmCompletion: 74, visitsCompleted: 21, tasksCompleted: 24 },
  { date: '2026-05-30', teamCompletion: 68, crmCompletion: 73, visitsCompleted: 20, tasksCompleted: 22 },
  { date: '2026-05-31', teamCompletion: 74, crmCompletion: 78, visitsCompleted: 23, tasksCompleted: 26 },
  { date: '2026-06-01', teamCompletion: 77, crmCompletion: 80, visitsCompleted: 24, tasksCompleted: 27 },
  { date: '2026-06-02', teamCompletion: 84, crmCompletion: 83, visitsCompleted: 28, tasksCompleted: 31 },
];

export const accountCoverageMetrics: AccountCoverageMetric[] = [
  {
    accountId: 'acct-acme',
    lastVisitDaysAgo: 1,
    visitsThisWeek: 3,
    engagementFrequency: 'High',
    riskScore: 22,
    pipelineHealth: 'Healthy',
    pipelineAmount: 42000,
  },
  {
    accountId: 'acct-globex',
    lastVisitDaysAgo: 11,
    visitsThisWeek: 1,
    engagementFrequency: 'Low',
    riskScore: 72,
    pipelineHealth: 'AtRisk',
    pipelineAmount: 78000,
  },
  {
    accountId: 'acct-initech',
    lastVisitDaysAgo: 3,
    visitsThisWeek: 2,
    engagementFrequency: 'Medium',
    riskScore: 38,
    pipelineHealth: 'Watch',
    pipelineAmount: 26000,
  },
  {
    accountId: 'acct-horizon',
    lastVisitDaysAgo: 22,
    visitsThisWeek: 0,
    engagementFrequency: 'Low',
    riskScore: 58,
    pipelineHealth: 'Watch',
    pipelineAmount: 85000,
  },
  {
    accountId: 'acct-northstar',
    lastVisitDaysAgo: 14,
    visitsThisWeek: 0,
    engagementFrequency: 'Medium',
    riskScore: 46,
    pipelineHealth: 'Healthy',
    pipelineAmount: 62000,
  },
  {
    accountId: 'acct-urban-foods',
    lastVisitDaysAgo: 26,
    visitsThisWeek: 0,
    engagementFrequency: 'Low',
    riskScore: 76,
    pipelineHealth: 'AtRisk',
    pipelineAmount: 54000,
  },
  {
    accountId: 'acct-atlas',
    lastVisitDaysAgo: 8,
    visitsThisWeek: 1,
    engagementFrequency: 'Medium',
    riskScore: 28,
    pipelineHealth: 'Healthy',
    pipelineAmount: 31000,
  },
  {
    accountId: 'acct-pinnacle',
    lastVisitDaysAgo: 17,
    visitsThisWeek: 0,
    engagementFrequency: 'Medium',
    riskScore: 52,
    pipelineHealth: 'Watch',
    pipelineAmount: 97000,
  },
];

export const territoryMetrics: TerritoryMetric[] = [
  { territory: 'Mexico City West', visitsCompleted: 10, travelRatio: 18, efficiency: 89 },
  { territory: 'Mexico City North', visitsCompleted: 4, travelRatio: 29, efficiency: 74 },
  { territory: 'Mexico City South', visitsCompleted: 5, travelRatio: 22, efficiency: 83 },
  { territory: 'Mexico City East', visitsCompleted: 3, travelRatio: 36, efficiency: 61 },
];

export const contacts: Contact[] = [
  { id: 'ct-1', accountId: 'acct-acme', name: 'Mariana Torres', role: 'Sales Director', phone: '+52 55 1000 1200', email: 'mariana@acme.example' },
  { id: 'ct-2', accountId: 'acct-globex', name: 'Javier Morales', role: 'Operations VP', phone: '+52 55 1000 1300', email: 'javier@globex.example' },
  { id: 'ct-3', accountId: 'acct-initech', name: 'Lucia Ramos', role: 'Customer Success Lead', phone: '+52 55 1000 1400', email: 'lucia@initech.example' },
  { id: 'ct-4', accountId: 'acct-horizon', name: 'Andres Valdez', role: 'Commercial Director', phone: '+52 55 1000 1500', email: 'andres@horizon.example' },
  { id: 'ct-5', accountId: 'acct-northstar', name: 'Camila Ortega', role: 'Procurement Lead', phone: '+52 55 1000 1600', email: 'camila@northstar.example' },
  { id: 'ct-6', accountId: 'acct-urban-foods', name: 'Sergio Ibarra', role: 'Operations Manager', phone: '+52 55 1000 1700', email: 'sergio@urbanfoods.example' },
  { id: 'ct-7', accountId: 'acct-atlas', name: 'Renata Cruz', role: 'VP Operations', phone: '+52 55 1000 1800', email: 'renata@atlas.example' },
  { id: 'ct-8', accountId: 'acct-pinnacle', name: 'Diego Flores', role: 'Buying Director', phone: '+52 55 1000 1900', email: 'diego@pinnacle.example' },
];

export const opportunities: Opportunity[] = [
  { id: 'opp-1', accountId: 'acct-acme', name: 'Route Intelligence Pilot', stage: 'Discovery', amount: 42000, probability: 35, nextStep: 'Confirm decision timeline' },
  { id: 'opp-2', accountId: 'acct-globex', name: 'Manufacturing Field CRM', stage: 'Proposal', amount: 78000, probability: 55, nextStep: 'Review budget next week' },
  { id: 'opp-3', accountId: 'acct-initech', name: 'Service Automation Add-on', stage: 'Closed Won', amount: 26000, probability: 100, nextStep: 'Schedule onboarding' },
  { id: 'opp-4', accountId: 'acct-horizon', name: 'Field Sales Visibility Rollout', stage: 'Proposal', amount: 85000, probability: 50, nextStep: 'Send revised ROI scenario' },
  { id: 'opp-5', accountId: 'acct-northstar', name: 'Coverage Analytics Renewal', stage: 'Negotiation', amount: 62000, probability: 65, nextStep: 'Align renewal stakeholders' },
  { id: 'opp-6', accountId: 'acct-urban-foods', name: 'Multi-site Expansion', stage: 'Pricing', amount: 54000, probability: 40, nextStep: 'Recover decision criteria' },
  { id: 'opp-7', accountId: 'acct-atlas', name: 'Operations Workflow Pilot', stage: 'Discovery', amount: 31000, probability: 30, nextStep: 'Share benchmark deck' },
  { id: 'opp-8', accountId: 'acct-pinnacle', name: 'Retail Execution Platform', stage: 'Evaluation', amount: 97000, probability: 45, nextStep: 'Book executive sponsor call' },
];

export const visits: ScheduledVisit[] = [
  { id: 'visit-1', accountId: 'acct-acme', time: '09:30', address: accounts[0].address, latitude: accounts[0].latitude, longitude: accounts[0].longitude, radiusMeters: 500, status: 'Scheduled' },
  { id: 'visit-2', accountId: 'acct-globex', time: '10:15', address: accounts[1].address, latitude: accounts[1].latitude, longitude: accounts[1].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-3', accountId: 'acct-initech', time: '11:00', address: accounts[2].address, latitude: accounts[2].latitude, longitude: accounts[2].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-4', accountId: 'acct-horizon', time: '11:45', address: accounts[3].address, latitude: accounts[3].latitude, longitude: accounts[3].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-5', accountId: 'acct-northstar', time: '12:30', address: accounts[4].address, latitude: accounts[4].latitude, longitude: accounts[4].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-6', accountId: 'acct-urban-foods', time: '13:15', address: accounts[5].address, latitude: accounts[5].latitude, longitude: accounts[5].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-7', accountId: 'acct-atlas', time: '14:00', address: accounts[6].address, latitude: accounts[6].latitude, longitude: accounts[6].longitude, radiusMeters: 450, status: 'Scheduled' },
  { id: 'visit-8', accountId: 'acct-pinnacle', time: '14:45', address: accounts[7].address, latitude: accounts[7].latitude, longitude: accounts[7].longitude, radiusMeters: 450, status: 'Scheduled' },
];

export const activities: ActivityEvent[] = [
  { id: 'act-1', accountId: 'acct-acme', title: 'Intro call', date: '2026-05-12', notes: 'Customer asked for mobile workflow examples.' },
  { id: 'act-2', accountId: 'acct-globex', title: 'Proposal sent', date: '2026-05-10', notes: 'Budget and timeline are the main blockers.' },
  { id: 'act-3', accountId: 'acct-initech', title: 'Implementation check-in', date: '2026-05-09', notes: 'Team requested follow-up automation.' },
  { id: 'act-4', accountId: 'acct-horizon', title: 'Proposal review', date: '2026-05-24', notes: 'Requested ROI scenario for regional rollout.' },
  { id: 'act-5', accountId: 'acct-northstar', title: 'Renewal call', date: '2026-06-01', notes: 'Procurement wants stakeholder map before renewal review.' },
  { id: 'act-6', accountId: 'acct-urban-foods', title: 'Pricing discussion', date: '2026-05-20', notes: 'Decision stalled after discount request.' },
  { id: 'act-7', accountId: 'acct-atlas', title: 'Operations discovery', date: '2026-06-06', notes: 'Asked for comparison against manual reporting.' },
  { id: 'act-8', accountId: 'acct-pinnacle', title: 'Vendor evaluation', date: '2026-05-29', notes: 'Executive sponsor is not yet identified.' },
];

export const initialTasks: Task[] = [
  { id: 'task-demo-1', accountId: 'acct-horizon', title: 'Send revised ROI scenario', dueDate: '2026-06-10', owner: 'Sofia Rivera', status: 'Open', priority: 'High', source: 'demo' },
  { id: 'task-demo-2', accountId: 'acct-urban-foods', title: 'Recover pricing discussion', dueDate: '2026-06-07', owner: 'Sofia Rivera', status: 'Open', priority: 'High', source: 'demo' },
  { id: 'task-demo-3', accountId: 'acct-northstar', title: 'Confirm renewal stakeholders', dueDate: '2026-06-17', owner: 'Sofia Rivera', status: 'Open', priority: 'Medium', source: 'demo' },
  { id: 'task-demo-4', accountId: 'acct-pinnacle', title: 'Book executive sponsor call', dueDate: '2026-06-14', owner: 'Sofia Rivera', status: 'Open', priority: 'High', source: 'demo' },
];

export const defaultInterviewQuestions: InterviewQuestion[] = [
  { id: 'q-1', prompt: 'How did the meeting go?', isActive: true, order: 1, category: 'meeting', answerType: 'text' },
  { id: 'q-2', prompt: 'Was the customer available?', isActive: true, order: 2, category: 'meeting', answerType: 'yesNo' },
  { id: 'q-3', prompt: 'How long did the visit last?', isActive: true, order: 3, category: 'meeting', answerType: 'duration' },
  { id: 'q-4', prompt: 'Did you discuss any new sales opportunities?', isActive: true, order: 4, category: 'opportunity', answerType: 'text' },
  { id: 'q-5', prompt: 'Was there any change in the opportunity stage?', isActive: true, order: 5, category: 'opportunity', answerType: 'text' },
  { id: 'q-6', prompt: 'Did any account information change?', isActive: true, order: 6, category: 'account', answerType: 'text' },
  { id: 'q-7', prompt: 'Would you like me to create a follow-up task?', isActive: true, order: 7, category: 'followUp', answerType: 'text' },
  { id: 'q-8', prompt: 'Should I schedule another meeting?', isActive: true, order: 8, category: 'followUp', answerType: 'yesNo' },
  { id: 'q-9', prompt: 'Do you want to assign any action items?', isActive: true, order: 9, category: 'followUp', answerType: 'text' },
];
